name: CI - Build , Trivy scan , Push to docker hub of the image
on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]
env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/devops-101
jobs:
  build-scan-push:
    name: Build -> scan -> Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set image tag from git SHA
        id : tag
        run: | 
          echo "SHA=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "Building tag: ${GITHUB_SHA::8}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.tag.outputs.SHA }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max
      - name: Trivy - Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
          image-ref:      "${{ env.IMAGE }}:${{ steps.tag.outputs.SHA }}"
          format:         "table"
          severity:       "CRITICAL,HIGH"
          exit-code:      "1"
          ignore-unfixed: "true"
      - name: Upload trivy scan results as artifact
        if: always() # Ensure this step runs even if the previous step fails
        uses: github/codeql-action/upload-artifact@v3
        with:
          sarif_file: trivy.sarif
      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.IMAGE }}:${{ steps.tag.outputs.SHA }}
          docker push ${{ env.IMAGE }}:latest